#
#
#
MD=/Volumes/rootfs

grafch:
	@install rc.local/thuria.sh $(MD)/etc/rc.local
	@install profile/putnamjm.tgz $(MD)/var/tmp
#	@install services/*.tgz $(MD)/var/tmp

xeno-dev:
	@install rc.local/xeno-dev.sh $(MD)/etc/rc.local
#	@install profile/putnamjm.tgz $(MD)/var/tmp

nfc:
	@install rc.local/helium.sh $(MD)/etc/rc.local
#	@install profile/putnamjm.tgz $(MD)/var/tmp
